INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (1,1,'a',10,8000);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (2,1,'a2',11,6500);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (3,2,'b',12,13000);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (4,2,'b2',13, 4500);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (5,3,'c',14, 3000);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (6,3,'c2',15,20000);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (7,4,'d',16,3000);
INSERT INTO L_ROW_NUMBER_OVER(TID, USER_TYPE, NAME, AGE, SALARY) VALUES (8,4,'d2',17, 18000);
